const userModel = require('../models/userModel');
const cartModel = require('../models/CartModel');
const cloudinary = require('cloudinary').v2;
let Cart = require('../models/localCartModel');
const path = require('path');
const fs = require('fs');
const formidable = require('formidable');

exports.index = async (req, res, next) => {
    // Get user
    user = res.locals.user;
    // Get orders
    orders = await cartModel.listofcartssameuser(res.locals.user._id);
    //render
    for (i = 0; i < orders.length; i++) {
        let cart = new Cart(orders[i]);
        orders[i].items = cart.generateArray();
    }
    console.log('carts:', orders);
    res.render('user/user', { user, orders });
};

exports.edit = async (req, res, next) => {
    const form = formidable({ multiples: true });
    let m_files;
    const formfields = await new Promise(function (resolve, reject) {
        form.parse(req, function (err, fields, files) {
            if (err) {
                reject(err);
                return;
            }
            console.log("within form.parse method, subject field of fields object is: " + fields);
            m_files = files;
            resolve(fields);
        }); // form.parse
    });

    const coverImage = m_files.coverImage;
    const imageName = 'user' + res.locals.user._id + "coverImg.jpg";
    if (coverImage && coverImage.size > 0) {
        let files = fs.readdirSync(path.join(__dirname,'..', 'public', 'images'));
        files.forEach(file => {
            if(file==imageName)
            fs.unlinkSync(path.join(__dirname,'..', 'public', 'images',imageName));
        });
        const oldPath = coverImage.path;
        const newPath = path.join(__dirname,'..', 'public', 'images',imageName);
        const rawData = fs.readFileSync(oldPath);
        fs.writeFile(newPath, rawData, function (err) {
            if (err) console.log("write file error:", err)
        })
    }
    let flag = 0;
    console.log(__dirname + '/../public/images/' + imageName);
    if (coverImage && coverImage.size > 0) {
        await cloudinary.uploader.upload(path.join(__dirname,'..', 'public', 'images',imageName), { public_id: formfields.name.replace(/ +/g, "") + "coverImg", folder: 'GameStore/Users', unique_filename: false, overwrite: true, "width": 265, "height": 265 })
            .then(function (image) {
                console.log("** File Upload (Promise)");
                console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
                console.log("* " + image.public_id);
                console.log("* " + image.url);
                formfields.cover = image.url;
                console.log("*formfields", formfields);
                flag = 1;
            })
            .catch(function (err) {
                console.log();
                console.log("*** File Upload (Promise)");
                console.log("*formfields", formfields);
                flag = 1;
                if (err) { console.warn(err); }
            });
    }

    if (flag != 0) {
        await userModel.updateuserById(res.locals.user._id, { name: formfields.name, birthday: formfields.birthday, phone: formfields.phone, email: formfields.email, cover: formfields.cover });
    }
    else {
        await userModel.updateuserById(res.locals.user._id, { name: formfields.name, birthday: formfields.birthday, phone: formfields.phone, email: formfields.email });
    }

    const user = await userModel.getUser(res.locals.user._id);;
    res.render('user/user', { user });

};

